site_name: BAS-Solutions
site_url: https://bas-solutions.com
nav:
  - Home: index.md
  - Shodan: shodan.md
  - TheHarvester: harvester.md
  - Escaneig: escaneig.md
  - Auditoria ssh: ssh.md
  - Enumeració: enumeracio.md
theme: readthedocs
